version: '3.8'

services:
  elasticsearch-hot:
    image: elastic/elasticsearch:8.7.0
    environment:
      - node.name=elasticsearch-hot
      - cluster.name=my-cluster
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-war
      - node.roles=master,data_content,data_hot,remote_cluster_client
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata-hot:/usr/share/elasticsearch/data

  elasticsearch-warm:
    image: elastic/elasticsearch:8.7.0
    environment:
      - node.name=elasticsearch-warm
      - cluster.name=my-cluster
      - node.roles=master,data_warm
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-warm
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false

    ports:
      - "9201:9200"
    volumes:
      - esdata-warm:/usr/share/elasticsearch/data

  logstash:
    image: elastic/logstash:8.7.0
    ports:
      - "5044:5044"
      - "5046:5046"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:Z
      - ./logstash/config/logstash.yml:/opt/logstash/config/logstash.yml:Z
    depends_on:
      - elasticsearch-hot
      - elasticsearch-warm

  kibana:
    image: kibana:8.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-hot:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-hot:9200","http://elasticsearch-warm:9200"]'
    depends_on:
      - elasticsearch-hot

  filebeat:
    image: elastic/filebeat:8.7.0
    privileged: true
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - /var/lib/docker:/var/lib/docker:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash

volumes:
  esdata-hot:
    driver: local
  esdata-warm:
    driver: local
